name: General workflow

on: [push]
    
jobs:
  lint:
    runs-on: ubuntu-18.04
    container: python:3.7.4-alpine3.10
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Install and run pylint
        run: |
          apk add --no-cache --update python3-dev gcc build-base 
          pip install pylint
          pip install --requirement requirements.txt
          pylint k8s-demo.py --disable=R,C,W0511
  build_and_publish:
    if: startsWith(github.ref, 'refs/tags/')
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-18.04
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: phoenixnap/bare-metal-cloud-demo-scripts/bare-metal-cloud-demo-scripts
          tags: latest,${{ env.GITHUB_BASE_REF_SLUG }}
